name: Test

on:
  pull_request:

jobs:
  run-my-action:
    name: Checks if this action works
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          action: deployment.create-revision
          project: mock-f2g-callback
          location: nortezh-1
          name: api
          image: ghcr.io/noz-acme/callback-tbp-be:487e6cf
          port: 3001
          type: WebService
        env:
          SA_AUTH_EMAIL: ${{ secrets.SA_AUTH_EMAIL }}
          SA_AUTH_KEY: ${{ secrets.SA_AUTH_KEY }}
