name: Test

on:
    pull_request:

jobs:
  run-my-action:
    name: Checks if this action works
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          action: deployment.create-revision
          project: "project-oei-1"
          location: "nortezh-stag"
          name: test-xxx
          image: nginx
          port: 85
          type: WebService
        env:
          SA_AUTH_EMAIL: ${{ secrets.SA_AUTH_EMAIL }}
          SA_AUTH_KEY: ${{ secrets.SA_AUTH_KEY }}